### ISSUE TITLE
Remove identation inconsistency

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/plexus-17#25]
The indentation value is set improperly. In many parts of the frontend, there are indentation of 2's and somewhere of 4's.

We would like to have indentation set to 2 everywhere. 
Keep in mind about the fact that majority of code is jsx so if using a formatter configure it accordingly.

The frontend code is in client/ dir and hopefully most of the inconsistency also. However do check the whole project for it. 
This could be a good way to understand the project structure and all the moving parts.

**Comment by kudapara** [comment]
I would like to work on this

**Comment by itaditya** [comment]
Go ahead @kudapara

**Comment by itaditya** [comment]
#26 closes this
